// Os 22 Arcanos Maiores — dados base do baralho tradicional (Rider-Waite-Smith).
export const MAJORS = [
  {
    n: 0, name: 'O Louco', roman: '0',
    keywords: ['recomeço', 'fé', 'liberdade', 'salto no desconhecido'],
    light: 'Um ciclo novo se abre e pede coragem inocente. Há espaço para experimentar sem o peso do que já foi.',
    shadow: 'Impulsividade, fuga das consequências e escolhas feitas sem qualquer preparo.',
    advice: 'Dê o primeiro passo mesmo sem enxergar o caminho inteiro, mas leve o mínimo necessário na mochila.',
    revKeywords: ['imprudência', 'medo de arriscar', 'dispersão'],
    revLight: 'Um convite a olhar antes de saltar: o entusiasmo precisa de direção.',
    revShadow: 'Ou você trava com medo do novo, ou se joga ignorando avisos claros.',
    revAdvice: 'Escolha conscientemente entre agir e esperar — a paralisia disfarçada de prudência também é uma decisão.',
  },
  {
    n: 1, name: 'O Mago', roman: 'I',
    keywords: ['manifestação', 'recursos', 'iniciativa', 'foco'],
    light: 'Você tem em mãos tudo o que precisa para começar. Vontade e habilidade se encontram.',
    shadow: 'Talento desperdiçado em muitas frentes ou usado para manipular.',
    advice: 'Nomeie um objetivo concreto e concentre nele os recursos que já possui.',
    revKeywords: ['manipulação', 'potencial parado', 'ilusão'],
    revLight: 'Hora de reconhecer onde você está enganando a si mesmo sobre suas reais intenções.',
    revShadow: 'Promessas maiores que a entrega, energia dispersa, jogos de poder.',
    revAdvice: 'Alinhe discurso e prática antes de pedir que confiem em você.',
  },
  {
    n: 2, name: 'A Sacerdotisa', roman: 'II',
    keywords: ['intuição', 'silêncio', 'mistério', 'sabedoria interna'],
    light: 'A resposta já existe dentro de você, mas só aparece no silêncio.',
    shadow: 'Informação retida, segredos que pesam, distância emocional.',
    advice: 'Antes de perguntar a alguém, escute o que você já sabe e evita admitir.',
    revKeywords: ['ruído mental', 'segredos', 'desconexão'],
    revLight: 'Convite a destravar o que foi guardado tempo demais.',
    revShadow: 'Intuição sufocada pela ansiedade e por opiniões externas.',
    revAdvice: 'Reduza o ruído: menos consultas, mais escuta própria.',
  },
  {
    n: 3, name: 'A Imperatriz', roman: 'III',
    keywords: ['abundância', 'criação', 'cuidado', 'sensualidade'],
    light: 'Algo cresce e pede nutrição: um projeto, um vínculo, um corpo que quer ser cuidado.',
    shadow: 'Excesso de zelo, controle disfarçado de cuidado, acomodação no conforto.',
    advice: 'Cuide do que plantou com constância — colheita é consequência de rotina, não de pressa.',
    revKeywords: ['bloqueio criativo', 'autodescuido', 'dependência'],
    revLight: 'Chamado a voltar o cuidado para dentro antes de doar mais.',
    revShadow: 'Você nutre todo mundo e esvazia a si mesmo.',
    revAdvice: 'Reserve um espaço do dia que exista só para o seu prazer.',
  },
  {
    n: 4, name: 'O Imperador', roman: 'IV',
    keywords: ['estrutura', 'autoridade', 'limites', 'estratégia'],
    light: 'A situação pede ordem, método e responsabilidade assumida.',
    shadow: 'Rigidez, autoritarismo e controle que sufocam o vivo.',
    advice: 'Defina regras claras — para os outros e, sobretudo, para você.',
    revKeywords: ['rigidez', 'falta de disciplina', 'abuso de poder'],
    revLight: 'Oportunidade de revisar quem manda na sua vida e por quê.',
    revShadow: 'Ou tudo vira controle, ou nada tem estrutura alguma.',
    revAdvice: 'Troque a imposição pelo combinado; troque o caos por um plano mínimo.',
  },
  {
    n: 5, name: 'O Hierofante', roman: 'V',
    keywords: ['tradição', 'aprendizado', 'valores', 'orientação'],
    light: 'Há sabedoria disponível em quem já percorreu esse caminho.',
    shadow: 'Dogma, conformismo e obediência sem sentido.',
    advice: 'Busque um mentor, um método ou um estudo formal para sustentar sua escolha.',
    revKeywords: ['ruptura', 'questionamento', 'caminho próprio'],
    revLight: 'Você está autorizado a criar sua própria regra.',
    revShadow: 'Rebeldia vazia, só para contrariar.',
    revAdvice: 'Pergunte quais crenças herdadas ainda te servem — e devolva o resto.',
  },
  {
    n: 6, name: 'Os Enamorados', roman: 'VI',
    keywords: ['escolha', 'união', 'valores', 'atração'],
    light: 'Um encontro significativo ou uma decisão que define quem você quer ser.',
    shadow: 'Indecisão crônica e escolhas feitas pelo desejo de agradar.',
    advice: 'Escolha a partir dos seus valores, não do medo de perder a outra opção.',
    revKeywords: ['desalinhamento', 'indecisão', 'conflito de valores'],
    revLight: 'Momento de revisar acordos que não representam mais os dois lados.',
    revShadow: 'Relações desequilibradas e decisões adiadas indefinidamente.',
    revAdvice: 'Diga o que você realmente quer, mesmo que isso desagrade.',
  },
  {
    n: 7, name: 'O Carro', roman: 'VII',
    keywords: ['vitória', 'direção', 'disciplina', 'avanço'],
    light: 'Forças opostas podem ser conduzidas juntas se houver rédea firme.',
    shadow: 'Pressa, agressividade e vitória a qualquer custo.',
    advice: 'Escolha um destino e mantenha o curso apesar dos desvios.',
    revKeywords: ['dispersão', 'perda de controle', 'estagnação'],
    revLight: 'Sinal para reduzir a velocidade e reencontrar o rumo.',
    revShadow: 'Esforço grande em direção nenhuma.',
    revAdvice: 'Pare, revise o destino e recomece com menos frentes abertas.',
  },
  {
    n: 8, name: 'A Força', roman: 'VIII',
    keywords: ['coragem serena', 'domínio interior', 'compaixão', 'paciência'],
    light: 'A força que resolve aqui é a da gentileza firme, não a do confronto.',
    shadow: 'Impulsos não digeridos, raiva reprimida ou explosiva.',
    advice: 'Trate o que te assusta com firmeza e carinho, como se doma sem violência.',
    revKeywords: ['insegurança', 'impaciência', 'autossabotagem'],
    revLight: 'Convite a recuperar a autoconfiança em passos pequenos.',
    revShadow: 'Dúvida sobre a própria capacidade e reações desproporcionais.',
    revAdvice: 'Cuide da sua energia antes de tentar controlar a situação.',
  },
  {
    n: 9, name: 'O Eremita', roman: 'IX',
    keywords: ['introspecção', 'busca', 'discernimento', 'solidão fértil'],
    light: 'Recolher-se é o que traz clareza agora. A luz vem de dentro.',
    shadow: 'Isolamento que vira fuga e distância de quem quer ajudar.',
    advice: 'Reserve tempo sozinho com a sua pergunta antes de decidir.',
    revKeywords: ['isolamento', 'recusa de ajuda', 'volta ao mundo'],
    revLight: 'Hora de sair da caverna e compartilhar o que você aprendeu.',
    revShadow: 'Solidão prolongada travestida de sabedoria.',
    revAdvice: 'Procure uma conversa honesta — você já pensou o suficiente.',
  },
  {
    n: 10, name: 'A Roda da Fortuna', roman: 'X',
    keywords: ['ciclos', 'virada', 'destino', 'timing'],
    light: 'O movimento chegou: algo gira a seu favor sem que você force.',
    shadow: 'Resistência à mudança e aposta cega na sorte.',
    advice: 'Aceite o novo ciclo e ajuste seus planos ao que mudou.',
    revKeywords: ['atraso', 'repetição', 'resistência'],
    revLight: 'Chance de quebrar um padrão que se repete há tempo demais.',
    revShadow: 'Sensação de má sorte e ciclos que voltam iguais.',
    revAdvice: 'Mude a sua parte da equação; o resto do giro não é seu.',
  },
  {
    n: 11, name: 'A Justiça', roman: 'XI',
    keywords: ['equilíbrio', 'verdade', 'consequência', 'acordos'],
    light: 'Cada ação está produzindo o resultado que lhe cabe. Há clareza jurídica ou ética.',
    shadow: 'Julgamento severo e frieza travestida de imparcialidade.',
    advice: 'Assuma sua responsabilidade e revise contratos e combinados com honestidade.',
    revKeywords: ['injustiça', 'desequilíbrio', 'evasão'],
    revLight: 'Momento de reparar o que ficou torto.',
    revShadow: 'Fuga da responsabilidade ou peso injusto sobre você.',
    revAdvice: 'Olhe os fatos sem defesa: onde a balança está desregulada?',
  },
  {
    n: 12, name: 'O Enforcado', roman: 'XII',
    keywords: ['pausa', 'entrega', 'nova perspectiva', 'sacrifício'],
    light: 'A espera tem função: de cabeça para baixo você enxerga o que estava invisível.',
    shadow: 'Martírio, estagnação voluntária e espera sem propósito.',
    advice: 'Suspenda a ação e mude o ângulo em vez de insistir na mesma força.',
    revKeywords: ['impaciência', 'apego', 'estagnação'],
    revLight: 'Fim de uma pausa longa — o movimento pode voltar.',
    revShadow: 'Você se sacrifica por algo que já não pede sacrifício.',
    revAdvice: 'Solte o que você segura só por medo de perder.',
  },
  {
    n: 13, name: 'A Morte', roman: 'XIII',
    keywords: ['fim', 'transformação', 'desapego', 'renascimento'],
    light: 'Um ciclo termina para que outro possa existir. O corte é limpo.',
    shadow: 'Medo do fim e prolongamento do que já morreu.',
    advice: 'Encerre com dignidade o que já acabou de fato.',
    revKeywords: ['resistência', 'luto travado', 'transição lenta'],
    revLight: 'A transformação está em curso, mesmo devagar.',
    revShadow: 'Agarrar-se ao passado impede o novo de chegar.',
    revAdvice: 'Nomeie exatamente o que precisa terminar e dê o primeiro passo.',
  },
  {
    n: 14, name: 'A Temperança', roman: 'XIV',
    keywords: ['equilíbrio', 'moderação', 'cura', 'paciência'],
    light: 'A mistura certa de elementos opostos gera cura e fluidez.',
    shadow: 'Excessos ou pressa que estragam o processo.',
    advice: 'Vá aos poucos, dosando esforço e descanso.',
    revKeywords: ['desequilíbrio', 'excesso', 'impaciência'],
    revLight: 'Aviso para reencontrar o próprio ritmo.',
    revShadow: 'Tudo ou nada, extremos que desgastam.',
    revAdvice: 'Corte um excesso concreto esta semana.',
  },
  {
    n: 15, name: 'O Diabo', roman: 'XV',
    keywords: ['apego', 'sombra', 'desejo', 'dependência'],
    light: 'Reconhecer o que te prende já afrouxa as correntes; há potência no desejo assumido.',
    shadow: 'Vícios, relações viciadas e materialismo que aprisiona.',
    advice: 'Pergunte o que você ganha ao permanecer preso — e se ainda vale.',
    revKeywords: ['libertação', 'consciência', 'ruptura'],
    revLight: 'Você está saindo de um padrão que te dominava.',
    revShadow: 'Recaídas e negação do próprio envolvimento.',
    revAdvice: 'Peça ajuda para romper o que sozinho você repete.',
  },
  {
    n: 16, name: 'A Torre', roman: 'XVI',
    keywords: ['ruptura', 'revelação', 'colapso', 'libertação abrupta'],
    light: 'A verdade derruba uma estrutura falsa — dói, mas liberta.',
    shadow: 'Crise, perdas súbitas e caos.',
    advice: 'Não reconstrua o mesmo prédio: examine a fundação.',
    revKeywords: ['crise adiada', 'medo da mudança', 'reconstrução'],
    revLight: 'O pior já passou e a reconstrução começou.',
    revShadow: 'Você segura de pé algo que já rachou.',
    revAdvice: 'Antecipe a queda inevitável em vez de esperar o desabamento.',
  },
  {
    n: 17, name: 'A Estrela', roman: 'XVII',
    keywords: ['esperança', 'inspiração', 'cura', 'fé renovada'],
    light: 'Depois do abalo vem a calmaria: há orientação e renovação.',
    shadow: 'Idealização e expectativa desconectada do real.',
    advice: 'Confie no processo e cuide do que te renova.',
    revKeywords: ['desânimo', 'descrença', 'desconexão'],
    revLight: 'Convite a reacender um propósito pequeno que seja.',
    revShadow: 'Perda de fé e cinismo protetor.',
    revAdvice: 'Volte ao que te fazia bem antes do cansaço.',
  },
  {
    n: 18, name: 'A Lua', roman: 'XVIII',
    keywords: ['ilusão', 'sonhos', 'medo', 'inconsciente'],
    light: 'O que é sentido antes de ser compreendido: sonhos e intuições trazem pistas.',
    shadow: 'Confusão, autoengano e ansiedade noturna.',
    advice: 'Não decida no escuro — colete fatos antes de concluir.',
    revKeywords: ['clareza', 'medos expostos', 'confusão dissipando'],
    revLight: 'A névoa começa a se dissipar e a verdade aparece.',
    revShadow: 'Ainda há autoengano em jogo.',
    revAdvice: 'Escreva o que te assusta: no papel, encolhe.',
  },
  {
    n: 19, name: 'O Sol', roman: 'XIX',
    keywords: ['alegria', 'clareza', 'sucesso', 'vitalidade'],
    light: 'Tudo fica visível e simples. Há alegria legítima e reconhecimento.',
    shadow: 'Otimismo ingênuo e exposição excessiva.',
    advice: 'Celebre e mostre — este é um momento de aparecer.',
    revKeywords: ['desânimo temporário', 'brilho ofuscado', 'atraso'],
    revLight: 'A alegria existe, mas está encoberta por cobranças.',
    revShadow: 'Autocrítica que apaga a própria luz.',
    revAdvice: 'Reconheça o que já deu certo antes de exigir mais.',
  },
  {
    n: 20, name: 'O Julgamento', roman: 'XX',
    keywords: ['despertar', 'balanço', 'chamado', 'perdão'],
    light: 'Um chamado interno pede resposta: é hora de avaliar e se reposicionar.',
    shadow: 'Autocrítica dura e culpa pelo passado.',
    advice: 'Faça as pazes com o que ficou e responda ao chamado.',
    revKeywords: ['dúvida', 'chamado ignorado', 'autojulgamento'],
    revLight: 'Chance de se perdoar e recomeçar sem tribunal interno.',
    revShadow: 'Adiar a decisão que você já sabe qual é.',
    revAdvice: 'Escute o chamado que você vem fingindo não ouvir.',
  },
  {
    n: 21, name: 'O Mundo', roman: 'XXI',
    keywords: ['conclusão', 'integração', 'realização', 'expansão'],
    light: 'Um ciclo se completa com aprendizado integrado. Há sensação de inteireza.',
    shadow: 'Ciclo que não fecha por falta de um último passo.',
    advice: 'Feche o que está quase pronto e celebre antes de abrir o próximo.',
    revKeywords: ['pendência', 'ciclo aberto', 'conclusão adiada'],
    revLight: 'Falta pouco: identifique o detalhe que trava o encerramento.',
    revShadow: 'Sensação de incompletude e metas eternamente adiadas.',
    revAdvice: 'Liste o que falta para dizer "terminei" e faça o menor item hoje.',
  },
];
