// Os 56 Arcanos Menores: 4 naipes x 14 cartas.
export const SUITS = [
  {
    id: 'wands', name: 'Paus', element: 'Fogo', symbol: '🜂', glyph: '⚚',
    theme: 'ação, criatividade, desejo e propósito',
    color: 'from-amber-500/30 to-rose-600/20',
  },
  {
    id: 'cups', name: 'Copas', element: 'Água', symbol: '🜄', glyph: '♥',
    theme: 'emoções, vínculos, afeto e intuição',
    color: 'from-sky-400/30 to-indigo-600/20',
  },
  {
    id: 'swords', name: 'Espadas', element: 'Ar', symbol: '🜁', glyph: '⚔',
    theme: 'mente, palavra, conflito e verdade',
    color: 'from-slate-300/30 to-cyan-600/20',
  },
  {
    id: 'pentacles', name: 'Ouros', element: 'Terra', symbol: '🜃', glyph: '⬤',
    theme: 'corpo, trabalho, dinheiro e concretude',
    color: 'from-emerald-400/30 to-yellow-600/20',
  },
];

export const RANKS = [
  { id: 'ace', label: 'Ás', num: 1, arch: 'semente e potencial puro do naipe' },
  { id: '2', label: 'Dois', num: 2, arch: 'escolha, par e equilíbrio inicial' },
  { id: '3', label: 'Três', num: 3, arch: 'primeiro resultado e expansão' },
  { id: '4', label: 'Quatro', num: 4, arch: 'estabilidade, pausa e consolidação' },
  { id: '5', label: 'Cinco', num: 5, arch: 'crise, perda e desafio' },
  { id: '6', label: 'Seis', num: 6, arch: 'ajuste, travessia e retomada' },
  { id: '7', label: 'Sete', num: 7, arch: 'avaliação, estratégia e persistência' },
  { id: '8', label: 'Oito', num: 8, arch: 'movimento acelerado e domínio' },
  { id: '9', label: 'Nove', num: 9, arch: 'quase-conclusão e balanço íntimo' },
  { id: '10', label: 'Dez', num: 10, arch: 'ápice, carga máxima e fim de ciclo' },
  { id: 'page', label: 'Pajem', num: 11, arch: 'aprendiz, curiosidade e notícia' },
  { id: 'knight', label: 'Cavaleiro', num: 12, arch: 'movimento, missão e intensidade' },
  { id: 'queen', label: 'Rainha', num: 13, arch: 'maturidade interna e cuidado do naipe' },
  { id: 'king', label: 'Rei', num: 14, arch: 'domínio externo e autoridade do naipe' },
];

// Essência de cada uma das 56 cartas: [luz, sombra, conselho]
export const MINOR_MEANINGS = {
  wands: {
    ace: ['Faísca criativa, um convite entusiasmado, vontade nova de começar.', 'Ideia que não sai do papel; empolgação sem continuidade.', 'Aceite o convite e faça algo concreto nas próximas 48 horas.'],
    '2': ['Planejamento de um voo maior; o mundo cabe na sua mão.', 'Ficar entre o conforto e o sonho, sem escolher.', 'Defina o destino antes de comprar a passagem.'],
    '3': ['Os primeiros resultados chegam e ampliam o horizonte.', 'Esperar retorno sem ter enviado nada.', 'Amplie o alcance: mostre seu trabalho a quem ainda não viu.'],
    '4': ['Celebração, casa, base sólida conquistada com trabalho.', 'Acomodação e medo de sair da zona segura.', 'Comemore o marco e depois abra a próxima porta.'],
    '5': ['Competição saudável que revela o seu tamanho real.', 'Conflitos de ego, ruído e disputa sem propósito.', 'Escolha suas batalhas: nem toda provocação merece resposta.'],
    '6': ['Reconhecimento público e vitória merecida.', 'Vaidade e dependência de aplauso.', 'Receba o crédito e agradeça quem carregou junto.'],
    '7': ['Defender sua posição com convicção, mesmo em minoria.', 'Estar sempre na defensiva, esgotado.', 'Sustente o essencial e solte a briga acessória.'],
    '8': ['Aceleração, notícias rápidas, tudo se move ao mesmo tempo.', 'Pressa que atropela detalhes importantes.', 'Aproveite a janela de velocidade, mas confira o alvo.'],
    '9': ['Resistência de quem já apanhou e continua de pé.', 'Desconfiança e armadura permanente.', 'Falta pouco: descanse sem abandonar o posto.'],
    '10': ['Compromisso levado até o fim, com peso e mérito.', 'Sobrecarga por não delegar nada.', 'Solte o que não é seu para carregar.'],
    page: ['Curiosidade ardente, vontade de aprender fazendo.', 'Entusiasmo disperso que troca de assunto a cada semana.', 'Experimente em pequena escala antes de prometer grande.'],
    knight: ['Coragem, aventura e ação impetuosa que quebra a inércia.', 'Impulsividade e projetos abandonados no meio.', 'Use o impulso, mas marque uma data de revisão.'],
    queen: ['Carisma caloroso e confiança que inspira os outros.', 'Ciúme, dramatização e necessidade de holofote.', 'Lidere pelo entusiasmo, não pela cobrança.'],
    king: ['Visão de longo prazo e liderança que abre caminho.', 'Autoritarismo e arrogância criativa.', 'Assuma a direção e delegue com clareza.'],
  },
  cups: {
    ace: ['Abertura do coração, novo afeto, sensibilidade transbordando.', 'Fechar-se por medo de sentir de novo.', 'Diga o que sente antes que o momento passe.'],
    '2': ['Encontro genuíno, parceria e reciprocidade.', 'Idealizar o outro ou se anular na relação.', 'Construa acordo de igual para igual.'],
    '3': ['Amizade, celebração e apoio da sua gente.', 'Vida social como fuga do que precisa ser sentido.', 'Chame quem te faz bem: você não precisa resolver sozinho.'],
    '4': ['Pausa emocional necessária para reavaliar o que te satisfaz.', 'Tédio, apatia e recusa do que é oferecido.', 'Repare na oportunidade que está bem ao seu lado.'],
    '5': ['Luto honesto por algo que realmente importava.', 'Fixar-se no que perdeu e ignorar o que restou.', 'Chore o copo entornado e depois olhe para trás: sobrou coisa boa.'],
    '6': ['Memória afetiva, ternura e reencontro com o passado.', 'Nostalgia que impede viver o presente.', 'Traga do passado o que ainda nutre, deixe o resto lá.'],
    '7': ['Muitas possibilidades e imaginação fértil.', 'Fantasia e escolhas confusas sem critério.', 'Elimine duas opções hoje: opções demais paralisam.'],
    '8': ['Partir em busca de sentido, mesmo deixando algo bom para trás.', 'Fugir sem encerrar o que ficou pendente.', 'Se já não te preenche, despeça-se com verdade.'],
    '9': ['Satisfação emocional, desejo realizado e gratidão.', 'Prazer superficial que não preenche de fato.', 'Reconheça o que já está bom antes de pedir mais.'],
    '10': ['Harmonia afetiva, família (de sangue ou escolhida) e pertencimento.', 'Idealizar a felicidade perfeita e cobrar isso dos outros.', 'Cuide dos vínculos com presença, não com performance.'],
    page: ['Mensagem afetuosa, sensibilidade nova e criatividade intuitiva.', 'Carência e sonhos infantilizados.', 'Confie no primeiro impulso do coração e depois verifique.'],
    knight: ['Romantismo, proposta sincera e movimento guiado pelo sentir.', 'Promessas encantadoras sem lastro.', 'Vá atrás do que te toca, mas peça consistência.'],
    queen: ['Empatia profunda, acolhimento e intuição madura.', 'Absorver a dor alheia até adoecer.', 'Sinta com o outro sem carregar por ele.'],
    king: ['Maturidade emocional: sentir muito e agir com serenidade.', 'Frieza controlada ou manipulação afetiva.', 'Nomeie a emoção e responda em vez de reagir.'],
  },
  swords: {
    ace: ['Clareza cortante, verdade dita, ideia que organiza tudo.', 'Palavra dura e uso da razão como arma.', 'Diga a verdade com precisão e sem crueldade.'],
    '2': ['Trégua necessária enquanto a decisão amadurece.', 'Evitar escolher e fingir que não há conflito.', 'Tire a venda: colete a informação que você evita.'],
    '3': ['Dor reconhecida é dor que pode ser curada.', 'Mágoa, traição e ruminação da ferida.', 'Deixe doer o tempo certo, sem reescrever a cena mil vezes.'],
    '4': ['Descanso mental e recuperação depois do estresse.', 'Exaustão ignorada até o colapso.', 'Pare de verdade: o problema aguarda algumas horas.'],
    '5': ['Perceber o custo real de vencer a discussão.', 'Vitória vazia, humilhação e ressentimento.', 'Ceda no que é orgulho e preserve o vínculo.'],
    '6': ['Travessia para águas mais calmas, mudança que alivia.', 'Levar a bagagem antiga para o novo lugar.', 'Aceite ajuda para atravessar; não precisa remar sozinho.'],
    '7': ['Estratégia, discrição e escolha do momento certo.', 'Meias-verdades, esquiva e desonestidade.', 'Se precisa esconder, revise o método.'],
    '8': ['Perceber que as amarras são, em grande parte, mentais.', 'Sentir-se preso e impotente sem testar as saídas.', 'Liste três saídas possíveis, mesmo as imperfeitas.'],
    '9': ['Trazer à luz a angústia que só aparece de madrugada.', 'Ansiedade, insônia e catastrofização.', 'Separe fato de medo no papel, item por item.'],
    '10': ['Fim doloroso, mas definitivo: o pior já aconteceu.', 'Vitimização e dramatização do golpe.', 'Aceite o encerramento; o amanhecer vem depois.'],
    page: ['Curiosidade investigativa e vontade de entender tudo.', 'Fofoca, crítica precipitada e vigilância excessiva.', 'Pergunte antes de concluir.'],
    knight: ['Foco afiado e ação rápida guiada por argumento.', 'Agressividade verbal e pressa que fere.', 'Desacelere a fala: nem tudo precisa ser respondido agora.'],
    queen: ['Discernimento honesto, independência e limites claros.', 'Frieza, sarcasmo e julgamento duro.', 'Fale a verdade com bordas suaves.'],
    king: ['Autoridade racional, ética e decisão baseada em fatos.', 'Rigidez intelectual e uso do saber como poder.', 'Decida com a cabeça, mas consulte o coração antes.'],
  },
  pentacles: {
    ace: ['Oportunidade concreta: proposta, recurso ou início material.', 'Deixar a chance passar por insegurança.', 'Aceite a oferta e organize o primeiro passo prático.'],
    '2': ['Malabarismo competente entre demandas e contas.', 'Instabilidade e sensação de nunca dar conta.', 'Reduza uma bola do ar antes que caiam todas.'],
    '3': ['Trabalho colaborativo e habilidade reconhecida.', 'Ego que atrapalha a construção coletiva.', 'Peça revisão de quem sabe mais que você.'],
    '4': ['Segurança construída e recursos preservados.', 'Avareza, controle e medo de perder.', 'Guarde o necessário e faça o resto circular.'],
    '5': ['Consciência da falta e do valor do apoio mútuo.', 'Escassez, exclusão e vergonha de pedir ajuda.', 'Bata na porta: a ajuda está mais perto do que parece.'],
    '6': ['Troca justa: dar e receber em proporção.', 'Dependência ou generosidade com preço embutido.', 'Reveja quem sustenta quem nessa relação.'],
    '7': ['Paciência com o que foi plantado e avaliação do rendimento.', 'Ansiedade por resultado e vontade de desistir.', 'Avalie os números antes de mudar de estratégia.'],
    '8': ['Dedicação ao ofício, aprimoramento e disciplina.', 'Trabalho mecânico sem sentido nem prazer.', 'Repita o fundamento: a maestria vem da constância.'],
    '9': ['Autossuficiência conquistada e prazer no próprio espaço.', 'Isolamento confortável e orgulho de não precisar de ninguém.', 'Desfrute do que você construiu sem culpa.'],
    '10': ['Estabilidade duradoura, legado e patrimônio compartilhado.', 'Prender-se a estruturas por obrigação familiar.', 'Pense em longo prazo: o que fica depois de você?'],
    page: ['Aprendizado prático, estudo e um plano ainda pequeno.', 'Procrastinação e planos eternamente na gaveta.', 'Comece pequeno, mas comece hoje.'],
    knight: ['Método, confiabilidade e progresso constante.', 'Lentidão, tédio e resistência a mudar de rota.', 'Mantenha a rotina: o passo lento chega longe.'],
    queen: ['Cuidado prático, hospitalidade e gestão generosa dos recursos.', 'Sobrecarga de cuidar de tudo e de todos.', 'Cuide do corpo e da casa como quem cuida do futuro.'],
    king: ['Prosperidade sólida, liderança prática e generosidade estável.', 'Materialismo e status como medida de valor.', 'Invista com prudência e compartilhe o resultado.'],
  },
};
